sudo: required

services:
  - docker


before_install:
  - docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD2"
  - docker build -t craftsmenlabs/gareth_dashboard .

script:
  - docker push craftsmenlabs/gareth_dashboard
