sudo: required

services:
  - docker

script:
  - docker build -t craftsmenlabs/gareth_dashboard .


after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD2"
  - 'if [ "$TRAVIS_PULL_REQUEST" != "false" ]; then docker push craftsmenlabs/gareth_dashboard; fi'

